### ISSUE TITLE
Can't find settings mentioned in Release Notes

### ISSUE THREAD

**Issue by jplatte** [JD342/arc-thunderbird-integration#5]
Okay, so this problem has already disappeared magically, but when I installed the extension, there was no additional settings, even restarting Thunderbird didn't help. Somehow clicking around in other parts of Thunderbird and trying again seems to have fixed it and now there is an additional tab in the display settings.

Maybe it would be a good idea to do the settings like [GNotifier](https://github.com/mkiol/GNotifier) does it, by having settings on the actual addon page, plus a settings button on the addon overview. Although the descriptions for the settings have an illegible text color when Arc Dark is set as the gtk theme, independently of whether your addon is installed. I imagine addons can't change the look of special pages like the addon page... EDIT: the TT DeepDark theme does change the look of the addons page, so this seems possible.
![bildschirmfoto vom 2017-06-12 18-06-01](https://user-images.githubusercontent.com/951129/27043279-da0e6d6e-4f99-11e7-9fea-36978b192183.png)

**Comment by nicolafio** [comment]
Agreed. In the next version I will move the section in the add-on page or add a button. I didn't include any styling in the add-on page. I think that the coloring is a visual bug of either Thunderbird or GNotifier when you switch to Arc Dark.

**Comment by nicolafio** [comment]
> TT DeepDark theme does change the look of the addons page, so this seems possible.

Yup. It is possible. It is in my list of things to do I put in the [notes section](https://github.com/JD342/arc-thunderbird-integration/blob/3658269f4025b0b8941cfafa13772bdd6fb11bde/readme.md#notes) at the end.

**Comment by jplatte** [comment]
The settings disappeared again after updating to 0.4.3. After clicking a message in my inbox and opening the settings again, it reappeared. Also, the theme reset back to the light one, this time not just visually, but also on the settings view.

**Comment by saymoncoppi** [comment]
Hey guys, some move to solve the issue of magical missing the settings options? I'd like to change the theme. 
My Thunderbird version is: 55.0b1 (64-bit)

**Comment by nicolafio** [comment]
In the [development branch](https://github.com/JD342/arc-thunderbird-integration/tree/dev) there is some work in progress that, among other things, includes commits that should address this issue ([b9d49f8](https://github.com/JD342/arc-thunderbird-integration/commit/b9d49f88addb054048f5e54d2ebc9d6ba2f79968) and [9475399](https://github.com/JD342/arc-thunderbird-integration/commit/94753991114407bf9ce8f3e3454ad08538d60276)). I'm not 100% certain that they are a complete fix though.

I was thinking about publishing these changes in the 5.0 version of the add-on. But let me know if you believe that this issue is urgent, and I will publish a new 0.4.x version that will have those specific changes.

By taking @jplatte's report into consideration, it seems that the preferences panel does appear eventually, and it will be possible to change the theme variant once that occurs. I am wondering if your case presents the issue of the preferences panel never showing up. Do you have this problem?

**Comment by KabbAmine** [comment]
Not sure if it helps, but I had the same problem not finding those settings, so I switched thunderbird's locale from russian to french, and same issue no settings shown, then I changed to english and they finally appear, and after enabling the dark theme, the settings are now always available with all the languages.

So IMO it may be related to the used local, and the settings are only shown if the language of thunderbird is english or if the settings were already changed before.

**Comment by nicolafio** [comment]
@KabbAmine I don't believe it is an issue related to the used local. I think it is due to the hacky/unstable way the settings panel is managed. Sometimes it appears and other times it does not. I will fix this problem once I have some spare time, but I promise it will be fixed in this month.

@jplatte As a side note, the development version of this extension on my machine also has some new styling in the mail and addons page. I will include these changes along with the fix.

<img src="https://user-images.githubusercontent.com/11964463/33514654-a906a310-d74f-11e7-883a-a0fccf877d5e.png" width=300/> <img src="https://user-images.githubusercontent.com/11964463/33514659-b2108976-d74f-11e7-9649-8a3ff6cde575.png" width=300/>

**Comment by nicolafio** [comment]
Version 0.5.0 should have this issue fixed.
